name: demo1

on: workflow_dispatch

jobs:
    This-is-the-first-job:
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: echo "${{ github.actor }} - this is demo workflow 1"